### ISSUE TITLE
consider concat-stream

### ISSUE THREAD

**Issue by anandthakker** [sindresorhus/get-stream#1]
Probably a good chance that you're already aware of concat-stream, but in case not: https://github.com/maxogden/concat-stream

If there's a reason that this wouldn't use that, it would be great to know in the README

**Comment by sindresorhus** [comment]
This one accepts a stream instead of being one and returns a promise instead of using a callback. The API is simpler and it only supports returning a string or buffer. It doesn't have a fragile type inference, you explicitly choose what you want. It supports back-pressure. And it doesn't depend on the huge `readable-stream` dependency.

Not interested in documenting differences. I mostly made it for my own needs. Don't really care if anyone uses this.
