### ISSUE TITLE
maxBuffer doesn't stop buffering data when reached

### ISSUE THREAD

**Issue by yocontra** [sindresorhus/get-stream#42]
Based on the docs it seems like maxBuffer would stop buffering data / end the stream once it hits the limit - currently it just rejects the promise but continues buffering data forever.

Two things that should be done:

- When the maxBuffer is reached, quit listening to the origin stream (and possibly add an option to end it)
- When maxBuffer is reached, set a boolean so https://github.com/sindresorhus/get-stream/blob/master/buffer-stream.js#L32 quits pushing to the array when the promise is rejected

**Comment by ehmicky** [comment]
The latest version fixed this issue. The stream is now read in a `for await` loop. When the `maxBuffer` is hit, this iteration stops, which means the stream is not read nor listened to anymore. The `chunks` variable what's been previously read, but this gets garbage collected once the function ends since it is a local variable.

Based on this, I believe this can be closed?
